# Generated by Django 4.1 on 2022-11-19 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='拠点')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='チャンネル')),
                ('channel_id', models.CharField(default='', max_length=50, unique=True, verbose_name='チャンネルID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='部署')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.base', verbose_name='拠点')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名前')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slack_id', models.CharField(max_length=30, unique=True, verbose_name='SlackID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.department', verbose_name='部署')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='団体名')),
                ('slack_app_token', models.CharField(max_length=100, unique=True, verbose_name='SlackAppToken')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='投稿日時')),
                ('base', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='analytics.base', verbose_name='拠点')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.channel', verbose_name='チャンネル')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.employee', verbose_name='メンバー')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='analytics.department', verbose_name='部署'),
        ),
        migrations.AddField(
            model_name='base',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analytics.organization', verbose_name='団体'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('channel', 'created_at', 'employee'), name='channel_date_employee_unique'),
        ),
        migrations.AddConstraint(
            model_name='base',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='name_organization_unique'),
        ),
    ]
